### ISSUE TITLE
Sparseness of semicolons causes errors when concatenating this script with other modules. 

### ISSUE THREAD

**Issue by askdesigners** [SonicHedgehog/angular-progress-button#2]
The last missing semicolon (ending the directive method call) causes angular to break when the script gets concatenated with other scripts. 

To recreate this issue, concat this script directly in front of another module and run the angular app.

**Comment by NicholasBoll** [comment]
I ran into this as well (after some debugging).

Tools like [bower-main-files](https://github.com/ck86/main-bower-files) create an array of files based on the `main` property in bower.json. Passing that output through a minifier will sometimes cause problems (depending on the dependency listed next).

The solution should be to either add the semicolon to the end of the source file or change the `main` property in bower.json to use the minified version. The solution is simple - not doing so can cause unsuspecting developers to waste time debugging.

**Comment by SonicHedgehog** [comment]
Fair enough, I have [added a closing semicolon in v0.2.0](https://github.com/SonicHedgehog/angular-progress-button/commit/f45186d768e06f7338da0041f1915983a765b889).
